### ISSUE TITLE
BaseToBinary ; BinaryToBase

### ISSUE THREAD

**Issue by Organic-Code** [TiWinDeTea/RadixSort-LO27#2]
Call :
BinaryToBase("1100101011001010", 16);

Returned value :
"3535"

Actual result :
"CACA"

Similar bug with BaseToBinary

**Comment by pinam45** [comment]
BaseNIntegerList.h:7 = \* Values(char*) are stored in reversed order (strongest weight at right)

1100101011001010 is just written in the wrong order for the lib

**Comment by Organic-Code** [comment]
Okey then
I thought these two were in Big endian anyway
